<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fully Paid Projects</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Helvetica', Arial, sans-serif; color: #1f2937; font-size: 12px; }
        .sheet { padding: 34px 40px; }
        .head { width: 100%; border-collapse: collapse; margin-bottom: 22px; }
        .head td { vertical-align: top; }
        .brand-name { font-size: 20px; font-weight: bold; color: #4f46e5; }
        .brand-sub { font-size: 11px; color: #6b7280; margin-top: 2px; }
        .doc-title { text-align: right; }
        .doc-title .t { font-size: 18px; font-weight: bold; color: #111827; }
        .doc-title .d { font-size: 10px; color: #9ca3af; margin-top: 4px; }
        .divider { border: none; border-top: 2px solid #eef0fe; margin: 0 0 20px; }
        .summary { background: #eef0fe; border-radius: 6px; padding: 12px 16px; margin-bottom: 20px; font-size: 12px; color: #3730a3; }
        .summary strong { font-size: 15px; }
        table.data { width: 100%; border-collapse: collapse; }
        table.data th { background: #4f46e5; color: #fff; font-size: 10px; text-transform: uppercase; letter-spacing: 0.4px; padding: 9px 10px; text-align: left; }
        table.data th.right { text-align: right; }
        table.data th.center { text-align: center; }
        table.data td { padding: 9px 10px; border-bottom: 1px solid #e5e7eb; font-size: 11px; color: #374151; }
        table.data td.right { text-align: right; }
        table.data td.center { text-align: center; }
        table.data tr:nth-child(even) td { background: #f9fafb; }
        .name { font-weight: bold; color: #111827; }
        .paid-tag { color: #15803d; font-weight: bold; }
        .foot { margin-top: 30px; padding-top: 12px; border-top: 1px solid #e5e7eb; text-align: center; font-size: 10px; color: #9ca3af; }
        .empty { padding: 24px; text-align: center; color: #9ca3af; }
    </style>
</head>
<body>
<div class="sheet">
    <table class="head">
        <tr>
            <td>
                <div class="brand-name">Prime Byte Software Solution</div>
                <div class="brand-sub">Accounting &amp; Project Management</div>
            </td>
            <td class="doc-title">
                <div class="t">FULLY PAID PROJECTS</div>
                <div class="d">Generated: {{ $generatedAt }}</div>
            </td>
        </tr>
    </table>
    <hr class="divider">

    @php
        $totalValue = $projects->sum('project_value');
        $totalCollected = $projects->sum('collected');
    @endphp
    <div class="summary">
        <strong>{{ $projects->count() }}</strong> fully paid project{{ $projects->count() === 1 ? '' : 's' }}
        &nbsp;·&nbsp; Total collected: <strong>Tk{{ number_format($totalCollected, 2) }}</strong>
    </div>

    @if($projects->isEmpty())
        <div class="empty">No fully paid projects to report.</div>
    @else
        <table class="data">
            <thead>
                <tr>
                    <th style="width:26px;">#</th>
                    <th>Project</th>
                    <th>Client</th>
                    <th>Type</th>
                    <th class="right">Value</th>
                    <th class="right">Collected</th>
                    <th class="center">Invoices</th>
                    <th class="center">Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($projects as $i => $project)
                    <tr>
                        <td>{{ $i + 1 }}</td>
                        <td class="name">{{ $project->name }}</td>
                        <td>{{ $project->client->name ?? '—' }}</td>
                        <td>{{ $project->type ?: '—' }}</td>
                        <td class="right">Tk{{ number_format($project->project_value, 2) }}</td>
                        <td class="right">Tk{{ number_format($project->collected, 2) }}</td>
                        <td class="center">{{ $project->invoices_count }}</td>
                        <td class="center paid-tag">PAID</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="foot">Generated by Prime Byte Software Solution · Computer-generated report.</div>
</div>
</body>
</html>
